defaults:
  - model: cnn
  - data: chest_ct
  - train: default
  - _self_

# General settings
seed: 42
experiment_name: ct_scan_classifier
output_dir: outputs/${experiment_name}

# Logging
wandb:
  project: CT_Scan_MLOps
  entity: mathiashl-danmarks-tekniske-universitet-dtu  # Team entity (all members must join this team)
  mode: online  # online, offline, disabled
  tags:
    - chest-ct
    - classification
    - mlops-course

# Paths
paths:
  data_dir: data/raw/chest-ctscan-images/Data
  models_dir: models
  logs_dir: logs
