name: Docker build

on:
  pull_request:
    branches: ["main", "master"]
    paths:
      - "Dockerfile*"
      - "dockerfiles/**"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/docker-build.yaml"

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build train image (CPU)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/train.dockerfile
          push: false
          tags: ct-scan-mlops:train

      - name: Build train image (CUDA)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/train_cuda.dockerfile
          push: false
          tags: ct-scan-mlops:train-cuda

      - name: Build API image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: dockerfiles/api.dockerfile
          push: false
          tags: ct-scan-mlops:api
